CREATE TABLE IF NOT EXISTS BOOKS (
  BOOK_KEY VARCHAR NOT NULL PRIMARY KEY,
  INFO.TITLE VARCHAR,
  INFO.AUTHOR VARCHAR,
  INFO.PUBLISHER VARCHAR,
  INFO.CATEGORY VARCHAR,
  PRICING.PRICE DOUBLE,
  METRICS.RATING DOUBLE,
  METRICS.SOLD_COUNT BIGINT
);

SELECT INFO.CATEGORY, COUNT(*) AS BOOK_COUNT, AVG(PRICING.PRICE) AS AVG_PRICE
FROM BOOKS
GROUP BY INFO.CATEGORY
ORDER BY BOOK_COUNT DESC;
